### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by ynskoroglu** [pantherdb/pantherapi-pyclient#1]
Hello I am trying to integrate statistical over-representation test into my code. I couldn't get any outputs for neither my result nor given tutorial inputs. I also didn't understand how output will form, can I get a json output like the one in the web service. Error is showed in screenshot.
![Untitled](https://user-images.githubusercontent.com/37922796/84480057-a1580f80-ac9c-11ea-9255-2829ca99c9e0.png)

**Comment by mugitty** [comment]
@ynskoroglu , the links were referring to the old URL.  I have updated them to point to the production system.

**Comment by ynskoroglu** [comment]
Thanks for the swift update, its working as of now. I would like to ask is there any possibility obtain results as json format with hierarchies preserved. Currently it only gives sorted results with no hierarchy. 
![image](https://user-images.githubusercontent.com/37922796/84578103-d5c9e980-adca-11ea-9c2f-8b9fed14fdb2.png)

**Comment by mugitty** [comment]
Currently there is no utility to obtain results in json format with the hierarchies preserved.
