### ISSUE TITLE
Multiple gene ID

### ISSUE THREAD

**Issue by harrlol** [pantherdb/pantherapi-pyclient#10]
On the Panther Web service, we could upload multiple gene lists under the "Select lists to analyze" tab. Is there an API equivalence of this function? I'm using the API to integrate this process in a larger workflow. My end goal is GO heat map, to get there, I am trying to obtain term overrepresentation analysis for multiple sample groups at once and from my understanding this algorithm functions similar to anova where a term that's significant when a sample group is analyzed by itself might not be significant if a new sample is added into the analysis, thus the simultaneous analysis is required for comparison between sample groups. Please let me know if I should provide more details!

**Comment by mugitty** [comment]
@harrlol, Currently the API does not support uploading of multiple gene lists

**Comment by harrlol** [comment]
Thanks for your prompt response!
