### ISSUE TITLE
An error "simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)" occurred

### ISSUE THREAD

**Issue by kim750a11** [pantherdb/pantherapi-pyclient#11]
Hi! My name is Yeon-Ki. Thank you for sharing your program.
pantherapi-pyclient.py, works fine. But if I use it for a rice gene "Os07g0615800" it gives simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)" occurs. Could help me how to solve it? 
For rice Oryza sativa, a geneinfo.json like geneinfoOsat.json {
  "organism": "39947"
}
was used.
Thanks in advance.

**Comment by mugitty** [comment]
Hi Yeon-Ki,

The issue has been resolved.  Thanks for reporting.

**Comment by kim750a11** [comment]
Hi! Mugitty,

Now it perfectly works.
Thanks a lot.

Yeon-Ki

2023년 12월 12일 (화) 오전 7:51, mugitty ***@***.***>님이 작성:

**Comment by kim750a11** [comment]
Hi!
This time, it gives the TypeError.
For a gene Os02g0795000 and organism=39947
it gives a result like,
3 mapped genes
PANTHER gene ID AnnotationDataset       Annotation Terms
Traceback (most recent call last):
  File
"/home/ykkim/Shell_Scripts/bioperls/Github/Pantherdb20231208/pantherapi-pyclient/pthr_go_annots.py_ori",
line 230, in <module>
    response.print_results()
  File
"/home/ykkim/Shell_Scripts/bioperls/Github/Pantherdb20231208/pantherapi-pyclient/pthr_go_annots.py_ori",
line 125, in print_results
    pthr_long_id = r['accession']
TypeError: string indices must be integers

If I try with curl like   curl -X POST "
https://pantherdb.org/services/oai/pantherdb/geneinfo?geneInputList=Os02g0795000&organism=39947"
-H "accept: application/json"
 it works.
I think web presentations have something to do.
Thanks,
Yeon-Ki

2023년 12월 12일 (화) 오전 9:56, Yeon-Ki Kim ***@***.***>님이 작성:

**Comment by kim750a11** [comment]
Hi!
I found the pantherdb expects multiple genes input in
https://pantherdb.org/services/oai/pantherdb/geneinfo?geneInputList=Os02g0795000,,,&organism=39947
<https://pantherdb.org/services/oai/pantherdb/geneinfo?geneInputList=Os02g0795000&organism=39947>

And the program gives a list for a multiple gene input. However, it gives a
dictionary for a single gene input.
So I modified  the program to check the isinstance of results (line 124).
The instance of results was checked with isinstance(results, list) for a
multiple gene input or isinstance(results, dict) for a single gene.
Best,
 Yeon-Ki


2023년 12월 12일 (화) 오전 10:42, Yeon-Ki Kim ***@***.***>님이 작성:
