### ISSUE TITLE
400 Bad Request when gene list longer than 3106 entries

### ISSUE THREAD

**Issue by j-miko** [pantherdb/pantherapi-pyclient#13]
Hi,

Some time ago I have written a simple PANTHER-DB API client as part of our lab's tools suite, basing on your code and the requests module. It was recently brought to my attention that it stops working when the list of queried gene IDs is long enough, irrespectable of the actual IDs. I have tested this myself and came to the conclusion that sending a query with more than 3106 (why the odd number?) IDs results in a 400 Bad Request response from the server:

`java.lang.IllegalArgumentException: Request header is too large`

3106 IDs work perfectly fine. At this point I'm not sure whether it's a server or client-side thing.

I'm attaching an example request that causes the issue:
[panther_error_request.txt](https://github.com/pantherdb/pantherapi-pyclient/files/13887608/panther_error_request.txt)

Thanks for your time.

**Comment by mugitty** [comment]
I noticed that you are using http instead of https.  The https forwarding functionality may not handle large requests.  I did try your data sample using a simple web page and it is working(see atttachment).   You need to change the extension of the file from .txt to .html
[sendPOST.txt](https://github.com/pantherdb/pantherapi-pyclient/files/13893667/sendPOST.txt)

**Comment by j-miko** [comment]
Thanks for the quick reply.

I tried over https and am getting the same 400 response.

**Comment by j-miko** [comment]
Okay, I got it working. Turns out I was passing the query using the 'params' parameter of requests.post(). This worked for smaller datasets but I guess it caused the hedaers to inflate with large enough ones. 

Passing the query using 'data' works fine over https.

Thanks for your help and sorry for any confusion.
